In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sentences = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [4]:
sentences

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
# Defining vocabulary size
voc_size = 10000

In [8]:
# One hot Representation
one_hot_repr = [one_hot(words, voc_size)for words in sentences]
one_hot_repr

[[3488, 6362, 3383, 932],
 [3488, 6362, 3383, 9988],
 [3488, 8970, 3383, 3125],
 [1794, 6084, 8156, 5551, 5171],
 [1794, 6084, 8156, 5551, 1242],
 [2821, 3488, 905, 3383, 6865],
 [4756, 6321, 3917, 5551]]

In [10]:
# Word embedding representation
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [15]:
sentences_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sentences_length)
embedded_docs

array([[   0,    0,    0,    0, 3488, 6362, 3383,  932],
       [   0,    0,    0,    0, 3488, 6362, 3383, 9988],
       [   0,    0,    0,    0, 3488, 8970, 3383, 3125],
       [   0,    0,    0, 1794, 6084, 8156, 5551, 5171],
       [   0,    0,    0, 1794, 6084, 8156, 5551, 1242],
       [   0,    0,    0, 2821, 3488,  905, 3383, 6865],
       [   0,    0,    0,    0, 4756, 6321, 3917, 5551]], dtype=int32)

In [16]:
# Feature representation
dimension = 10

In [18]:
model = Sequential()
model.add(Embedding(voc_size, dimension, input_length=sentences_length))
model.compile("adam", "mse")

In [19]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 257ms/step


array([[[ 0.01834584,  0.02669624,  0.0117907 ,  0.0239338 ,
         -0.02120179,  0.04502007, -0.00454843,  0.00500691,
          0.01408874, -0.03858634],
        [ 0.01834584,  0.02669624,  0.0117907 ,  0.0239338 ,
         -0.02120179,  0.04502007, -0.00454843,  0.00500691,
          0.01408874, -0.03858634],
        [ 0.01834584,  0.02669624,  0.0117907 ,  0.0239338 ,
         -0.02120179,  0.04502007, -0.00454843,  0.00500691,
          0.01408874, -0.03858634],
        [ 0.01834584,  0.02669624,  0.0117907 ,  0.0239338 ,
         -0.02120179,  0.04502007, -0.00454843,  0.00500691,
          0.01408874, -0.03858634],
        [ 0.02670356,  0.02803702,  0.02437624, -0.02621281,
          0.00699458,  0.01200442, -0.02281588,  0.0225199 ,
          0.03631404, -0.01722495],
        [-0.04926078,  0.00428281, -0.00284704,  0.02564533,
         -0.03264584,  0.00611939,  0.01169439, -0.01587563,
         -0.00135101,  0.04529654],
        [-0.03557537, -0.02418084,  0.01087136, -0.0

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 3488, 6362, 3383,  932], dtype=int32)